data:
  img_dir: /root/autodl-tmp/Glas/Image
  lbl_dir: /root/autodl-tmp/Glas/Label
  img_size: 512
  batch_size: 8
  num_workers: 4
  n_samples: null

model:
  type: unet
  in_channels: 3
  out_channels: 1
  features: [64, 128, 256, 512]

train:
  epochs: 100
  lr: 0.0001
  save_dir: results/unet
